<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tile;

/**
 * TileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TileRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * return a random tile of type "island"
     * @return Tile
     */
    public function getRandomIsland(): ?Tile
    {
        $query = $this->createQueryBuilder('t')
            ->select('t');
        $expr = $query->expr();

        $query->where(
            $expr->eq(
                't.type',
                $expr->literal('island')
            )
        )
            ->orderBy('RAND()')
            ->setMaxResults(1);

        return $query->getQuery()->getSingleResult();
    }

    /**
     * remove all treasure flag from tiles
     */
    public function clearTreasure(): void
    {
        $query = $this->createQueryBuilder('t')
            ->update()
            ->set('t.hasTreasure', 0)
            ->where('t.hasTreasure = 1')
            ->getQuery()
            ->execute();
    }
}
